### ISSUE TITLE
Catergorises the entries and tablulate them

### ISSUE THREAD

**Issue by Nerajno** [tuckpuck/awesome-programming-podcasts#1]
- [x] Put them into categorizes based  on topics and areas covered. 
- [x] Put them in tables for readability, example below : 

| Name  | Available on Apple | Etc |
| ------------- | ------------- | ------------ |
| Name  | Yes (being a link)  |   No ( with no link ) |

**Comment by tuckpuck** [comment]
Great idea! It has been updated with the formatting mentioned. Thanks.
